-- MySQL Script generated by MySQL Workbench
-- Wed Apr  3 21:44:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema p2p
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema p2p
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `p2p` DEFAULT CHARACTER SET utf8 ;
USE `p2p` ;

-- -----------------------------------------------------
-- Table `p2p`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p2p`.`user` (
  `id` BIGINT NOT NULL,
  `mobile` VARCHAR(11) NULL,
  `pass` VARCHAR(45) NULL,
  `IDCard` VARCHAR(45) NULL COMMENT 'Identify card',
  `invitor` VARCHAR(45) NULL COMMENT '邀请人',
  `createDate` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p2p`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p2p`.`project` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL COMMENT '借款人',
  `loanMoney` DECIMAL(8,2) NULL COMMENT '借款金额',
  `code` VARCHAR(45) NULL COMMENT '项目代码',
  `loanWay` VARCHAR(45) NULL COMMENT '借款方式',
  `loanTime` INT NULL COMMENT '借款多久,单位：月。',
  `zhl` DECIMAL(4,2) NULL COMMENT '年利率',
  `description` VARCHAR(45) NULL,
  `createDate` DATETIME NULL COMMENT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
